name: Conradzen
favicon: null
layout_spectrum: 0.6965719896834344
typography_spectrum: 0.4988877873402089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3400733408052474
  lightness: 0.2863121519330889
  saturation: 0.6667735832743347
  rhythmicContrast: 0.8457034756429493
purpose: []
